services:
  eclipse-hotel:
    container_name: eclipse-hotel
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - hotel-network

  postgres:
    image: 'postgres:latest'
    container_name: eclipse-hotel_db
    environment:
      - 'POSTGRES_DB=eclipse-hotel'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=erika'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hotel-network

volumes:
  postgres_data:

networks:
  hotel-network: