services:
  eclipse-hotel:
    image: 'eclipse-hotel:latest'
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - network

  postgres:
    image: 'postgres:latest'
    container_name: db
    environment:
      - 'POSTGRES_DB=eclipse-hotel'
      - 'POSTGRES_PASSWORD=pass'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - network
    depends_on:
      - eclipse-hotel

volumes:
  data:

networks:
  network: